### ISSUE TITLE
Treat optionals as `JSON.null` to remove all the explicit unwrapping

### ISSUE THREAD

**Issue by helje5** [saoudrizwan/DynamicJSON#4]
The thing you present primarily looks ugly because of the optional chaining at every single step:

    if let street = json.person?.address?[0].street.stringValue { }

But it doesn't have to be like that (it is dynamic anyways). I think you could improve that a lot by essentially adding "nil messaging":

    if let street = json.person.address[0].street.stringValue { .. }

Instead of returning an optional in every item of the chain, only make the leaf accessors (`stringValue`, `intValue`, etc) optional. When a lookup is not successful, return `JSON.null` (which itself returns `JSON.null` on all JSON accesses, so that the result propagates).

If you'd like you could also add a `JSON.lookupError(parent, key)` as a result for missed lookups for debugging purposes (and which also propagates down the call chain, and could even persist the lookup path from the root of the first lookup failure).

**Comment by saoudrizwan** [comment]
Thank you for the awesome suggestion, I just implemented this in version 2.0.0. Give it a try and let me know how you like it!

**Comment by helje5** [comment]
Not worth a notable mention? 😜

**Comment by saoudrizwan** [comment]
[It absolutely is 😉](https://github.com/saoudrizwan/DynamicJSON/commit/509a7451a2a39f05a1d41ee74ac7e10dc8b7deeb)
