### ISSUE TITLE
JSON values aren't decomposed in JSON dictionary literals

### ISSUE THREAD

**Issue by WilsonGramer** [saoudrizwan/DynamicJSON#6]
Composing a dictionary literal with JSON properties results in those properties being null, instead of decomposing them into dictionaries themselves. For example, when
```swift
let foo = ["foo": 3] as JSON
let bar = ["bar": foo] as JSON
```
`bar` should equal
```swift 
[
    "foo": [
        "bar": 3
    ]
] as JSON
```
However, `bar` actually equals
```swift
[
    "foo": JSON.null
] as JSON
```

To fix this issue, the `JSON.init(_ object: Any)` initializer should set `self` to `object` when `object` is an instance of `JSON`. I'll submit a PR for this later today; let me know what you think!

**Comment by saoudrizwan** [comment]
Thanks for pointing this out. I just pushed a fix in version 2.0.2
